require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CoreValuesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CoreValue. As you add validations to CoreValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoreValuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all core_values as @core_values" do
      core_value = CoreValue.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:core_values)).to eq([core_value])
    end
  end

  describe "GET show" do
    it "assigns the requested core_value as @core_value" do
      core_value = CoreValue.create! valid_attributes
      get :show, {:id => core_value.to_param}, valid_session
      expect(assigns(:core_value)).to eq(core_value)
    end
  end

  describe "GET new" do
    it "assigns a new core_value as @core_value" do
      get :new, {}, valid_session
      expect(assigns(:core_value)).to be_a_new(CoreValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested core_value as @core_value" do
      core_value = CoreValue.create! valid_attributes
      get :edit, {:id => core_value.to_param}, valid_session
      expect(assigns(:core_value)).to eq(core_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoreValue" do
        expect {
          post :create, {:core_value => valid_attributes}, valid_session
        }.to change(CoreValue, :count).by(1)
      end

      it "assigns a newly created core_value as @core_value" do
        post :create, {:core_value => valid_attributes}, valid_session
        expect(assigns(:core_value)).to be_a(CoreValue)
        expect(assigns(:core_value)).to be_persisted
      end

      it "redirects to the created core_value" do
        post :create, {:core_value => valid_attributes}, valid_session
        expect(response).to redirect_to(CoreValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved core_value as @core_value" do
        post :create, {:core_value => invalid_attributes}, valid_session
        expect(assigns(:core_value)).to be_a_new(CoreValue)
      end

      it "re-renders the 'new' template" do
        post :create, {:core_value => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested core_value" do
        core_value = CoreValue.create! valid_attributes
        put :update, {:id => core_value.to_param, :core_value => new_attributes}, valid_session
        core_value.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested core_value as @core_value" do
        core_value = CoreValue.create! valid_attributes
        put :update, {:id => core_value.to_param, :core_value => valid_attributes}, valid_session
        expect(assigns(:core_value)).to eq(core_value)
      end

      it "redirects to the core_value" do
        core_value = CoreValue.create! valid_attributes
        put :update, {:id => core_value.to_param, :core_value => valid_attributes}, valid_session
        expect(response).to redirect_to(core_value)
      end
    end

    describe "with invalid params" do
      it "assigns the core_value as @core_value" do
        core_value = CoreValue.create! valid_attributes
        put :update, {:id => core_value.to_param, :core_value => invalid_attributes}, valid_session
        expect(assigns(:core_value)).to eq(core_value)
      end

      it "re-renders the 'edit' template" do
        core_value = CoreValue.create! valid_attributes
        put :update, {:id => core_value.to_param, :core_value => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested core_value" do
      core_value = CoreValue.create! valid_attributes
      expect {
        delete :destroy, {:id => core_value.to_param}, valid_session
      }.to change(CoreValue, :count).by(-1)
    end

    it "redirects to the core_values list" do
      core_value = CoreValue.create! valid_attributes
      delete :destroy, {:id => core_value.to_param}, valid_session
      expect(response).to redirect_to(core_values_url)
    end
  end

end
